### ISSUE TITLE
newest commit/6eb93c4 build failed

### ISSUE THREAD

**Issue by debiansid** [shadowsocks/shadowsocks-libev#1805]
### What version of shadowsocks-libev are you using?
newest commit

### What operating system are you using?
debian wheezy on mips

### What did you do?
dpkg-buildpackage -b -us -uc -d

### What did you expect to see?
build deb successful

### What did you see instead?
```
 CC     libshadowsocks_libev_la-netutils.lo
  CC     libshadowsocks_libev_la-local.lo
local.c: In function 'server_recv_cb':
local.c:397:25: error: 's' undeclared (first use in this function)
local.c:397:25: note: each undeclared identifier is reported only once for each function it appears in
local.c: In function 'remote_recv_cb':
local.c:945:41: error: 'TCP_NODELAY' undeclared (first use in this function)
local.c: In function 'create_remote':
local.c:1174:35: error: 'TCP_NODELAY' undeclared (first use in this function)
local.c: In function 'accept_cb':
local.c:1248:35: error: 'TCP_NODELAY' undeclared (first use in this function)
make[3]: *** [libshadowsocks_libev_la-local.lo] Error 1
make[3]: Leaving directory `/home/user/shadowsocks-libev/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/user/shadowsocks-libev'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/user/shadowsocks-libev'
dh_auto_build: make -j1 returned exit code 2
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```

**Comment by wongsyrone** [comment]
> local.c: In function 'remote_recv_cb':
local.c:945:41: error: 'TCP_NODELAY' undeclared (first use in this function)
local.c: In function 'create_remote':
local.c:1174:35: error: 'TCP_NODELAY' undeclared (first use in this function)
local.c: In function 'accept_cb':
local.c:1248:35: error: 'TCP_NODELAY' undeclared (first use in this function)

use ./autogen.sh to regenerate configure script

> local.c: In function 'server_recv_cb':
local.c:397:25: error: 's' undeclared (first use in this function)

What's your kernel version? In this case, all tcp fast open related symbols are not found.

**Comment by debiansid** [comment]
'
uname -a
Linux debian-mips 3.2.0-4-5kc-malta #1 Debian 3.2.51-1 mips64 GNU/Linux
`
I have no idea how to generate configure script under dpkg-buildpackage, because I build deb on qemu host not the target machine which is running shadowsocks-libev client.

**Comment by debiansid** [comment]
I managed to upgrade kernel to `Linux debian-mips 3.16.0-0.bpo.4-5kc-malta #1 Debian 3.16.7-ckt25-2~bpo70+1 (2016-04-12) mips64 GNU/Linux`
and enabled TFO , still same error

**Comment by madeye** [comment]
Try the latest commit.

**Comment by debiansid** [comment]
after upgrade kernel to 3.16, I thought I should have TCP_FASTOPEN , my question should be how to check if I have it or not?
btw
lastest commit works but without TFO I guess.

**Comment by madeye** [comment]
Try update your kernel header as well:

`sudo apt-get install linux-headers-$(uname -r)`

**Comment by debiansid** [comment]
same error after installed linux-headers
```
make[3]: Entering directory `/home/user/shadowsocks-libev/src'
  CC     libshadowsocks_libev_la-utils.lo
  CC     libshadowsocks_libev_la-jconf.lo
  CC     libshadowsocks_libev_la-json.lo
  CC     libshadowsocks_libev_la-udprelay.lo
  CC     libshadowsocks_libev_la-cache.lo
  CC     libshadowsocks_libev_la-acl.lo
  CC     libshadowsocks_libev_la-netutils.lo
  CC     libshadowsocks_libev_la-local.lo
local.c: In function 'server_recv_cb':
local.c:396:24: error: 's' may be used uninitialized in this function [-Werror=uninitialized]
cc1: all warnings being treated as errors
make[3]: *** [libshadowsocks_libev_la-local.lo] Error 1
make[3]: Leaving directory `/home/user/shadowsocks-libev/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/user/shadowsocks-libev'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/user/shadowsocks-libev'
dh_auto_build: make -j1 returned exit code 2
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```

**Comment by debiansid** [comment]
and I git clone another copy to local build host, got this error
```
user@debian-mips:~/shadowsocks-libev-new$ dpkg-buildpackage -b -us -uc -d
dpkg-buildpackage: source package shadowsocks-libev
dpkg-buildpackage: source version 3.1.1-1
dpkg-buildpackage: source changed by Max Lv <max.c.lv@gmail.com>
dpkg-buildpackage: host architecture mips
 dpkg-source --before-build shadowsocks-libev-new
 fakeroot debian/rules clean
dh clean
   dh_testdir
   dh_auto_clean
   dh_clean
 debian/rules build
make: `build' is up to date.
 fakeroot debian/rules binary
dh binary
   dh_testdir
   debian/rules override_dh_auto_configure
make[1]: Entering directory `/home/user/shadowsocks-libev-new'
# Whether to have stack-protector is decided by dpkg-buildflags.
# So --disable-ssp here should be safe. See Bug#829498
dh_auto_configure -- \
                --enable-shared \
                --disable-ssp
CMake Error: The source directory "/home/user/shadowsocks-libev-new/obj-mips-linux-gnu/--disable-ssp" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON --enable-shared --disable-ssp returned exit code 1
make[1]: *** [override_dh_auto_configure] Error 2
make[1]: Leaving directory `/home/user/shadowsocks-libev-new'
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
```

**Comment by debiansid** [comment]
fixed by https://github.com/shadowsocks/shadowsocks-libev/commit/79f0e3c68d00eea2456f1e668b00bea93ce673ce
