### ISSUE TITLE
didn't compile in gcc 5.3

### ISSUE THREAD

**Issue by ahxxm** [shadowsocks/shadowsocks-libev#627]
Environment: inside alpine container, setup command `apk add autoconf build-base curl libtool linux-headers openssl-dev unzip`, rev `a73fe213a6bc165d402fd1cae7f51018ccd53aa3`

Output:
```
make[2]: Entering directory '/shadowsocks-libev-master/src'
  CC       libshadowsocks_la-utils.lo
  CC       libshadowsocks_la-jconf.lo
  CC       libshadowsocks_la-json.lo
  CC       libshadowsocks_la-encrypt.lo
  CC       libshadowsocks_la-udprelay.lo
  CC       libshadowsocks_la-cache.lo
  CC       libshadowsocks_la-acl.lo
  CC       libshadowsocks_la-netutils.lo
netutils.c: In function 'bind_to_address':
netutils.c:95:40: error: passing argument 2 of 'bind' from incompatible pointer type [-Werror=incompatible-pointer-types]
                 return bind(socket_fd, addr, sizeof(struct sockaddr_in));
                                        ^
In file included from /usr/include/fortify/sys/socket.h:20:0,
                 from netutils.c:36:
/usr/include/sys/socket.h:295:5: note: expected 'const struct sockaddr *' but argument is of type 'struct sockaddr_in *'
 int bind (int, const struct sockaddr *, socklen_t);
     ^
netutils.c:100:40: error: passing argument 2 of 'bind' from incompatible pointer type [-Werror=incompatible-pointer-types]
                 return bind(socket_fd, addr, sizeof(struct sockaddr_in6));
                                        ^
In file included from /usr/include/fortify/sys/socket.h:20:0,
                 from netutils.c:36:
/usr/include/sys/socket.h:295:5: note: expected 'const struct sockaddr *' but argument is of type 'struct sockaddr_in6 *'
 int bind (int, const struct sockaddr *, socklen_t);
     ^
cc1: all warnings being treated as errors
Makefile:763: recipe for target 'libshadowsocks_la-netutils.lo' failed
make[2]: *** [libshadowsocks_la-netutils.lo] Error 1
make[2]: Leaving directory '/shadowsocks-libev-master/src'
Makefile:549: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/shadowsocks-libev-master'
Makefile:371: recipe for target 'all' failed
make: *** [all] Error 2
```
